from __future__ import annotations

import csv
from io import BytesIO, StringIO
from typing import Iterable

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def build_actions_export_csv(rows: Iterable[dict]) -> bytes:
    output = StringIO(newline="")
    headers = [
        "id",
        "title",
        "case_number",
        "court",
        "department_name",
        "priority",
        "item_type",
        "due_date",
        "days_remaining",
        "status",
        "description",
    ]
    writer = csv.DictWriter(output, fieldnames=headers, extrasaction="ignore")
    writer.writeheader()
    for row in rows:
        export_row = {
            "id": str(row.get("id")),
            "title": row.get("title"),
            "case_number": row.get("case_number"),
            "court": row.get("court"),
            "department_name": row.get("department_name"),
            "priority": row.get("priority_badge"),
            "item_type": row.get("item_type"),
            "due_date": row.get("due_date"),
            "days_remaining": row.get("days_remaining"),
            "status": row.get("status_chip"),
            "description": row.get("description"),
        }
        writer.writerow(export_row)
    return output.getvalue().encode("utf-8")


def _build_header_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica-Bold", 10)
    canvas.drawString(40, 770, "Official Use Only")
    canvas.setFont("Helvetica", 8)
    canvas.drawString(40, 756, "LAOS Verified Action Plan Summary Report")
    canvas.drawRightString(550, 770, "Confidential")
    canvas.line(40, 748, 560, 748)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(40, 30, f"Generated by LAOS")
    canvas.drawRightString(550, 30, f"Page {doc.page}")
    canvas.restoreState()


def generate_dashboard_summary_pdf(summary: dict, department_breakdown: Iterable[dict], urgent_items: Iterable[dict]) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=80, bottomMargin=50, leftMargin=40, rightMargin=40)
    styles = getSampleStyleSheet()
    body_style = styles["BodyText"]
    body_style.spaceAfter = 12
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], fontSize=18, leading=22)
    section_style = ParagraphStyle("Section", parent=styles["Heading2"], fontSize=12, leading=14)

    elements = [
        Paragraph("Verified Action Plan Summary", title_style),
        Spacer(1, 12),
        Paragraph(f"Total verified actions: {summary.get('total_verified_items', 0)}", body_style),
        Paragraph(f"Overdue actions: {summary.get('overdue_items_count', 0)}", body_style),
        Paragraph(f"Due within 7 days: {summary.get('due_within_7_days', 0)}", body_style),
        Paragraph(f"Due within 30 days: {summary.get('due_within_30_days', 0)}", body_style),
        Spacer(1, 16),
        Paragraph("Department breakdown", section_style),
    ]

    breakdown_rows = [["Department", "Verified Actions", "Overdue"]]
    for department in department_breakdown:
        breakdown_rows.append(
            [
                department.get("department_name"),
                str(department.get("item_count", 0)),
                str(department.get("overdue_count", 0)),
            ]
        )
    table = Table(breakdown_rows, hAlign="LEFT", colWidths=[220, 120, 120])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 18))
    elements.append(Paragraph("Urgent actions", section_style))

    urgent_rows = [["Title", "Department", "Priority", "Due Date", "Status"]]
    for item in urgent_items:
        urgent_rows.append(
            [
                item.get("title"),
                item.get("department_name") or "Unassigned",
                item.get("priority_badge"),
                str(item.get("due_date") or "TBD"),
                item.get("status_chip"),
            ]
        )
    urgent_table = Table(urgent_rows, hAlign="LEFT", colWidths=[170, 110, 90, 80, 100])
    urgent_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f8f8f8")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    elements.append(urgent_table)
    doc.build(elements, onFirstPage=_build_header_footer, onLaterPages=_build_header_footer)
    return buffer.getvalue()


def generate_case_report_pdf(case_data: dict, action_items: Iterable[dict]) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=80, bottomMargin=50, leftMargin=40, rightMargin=40)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], fontSize=18, leading=22)
    section_style = ParagraphStyle("Section", parent=styles["Heading2"], fontSize=12, leading=14)
    body_style = styles["BodyText"]
    body_style.spaceAfter = 10

    elements = [
        Paragraph("Case Report", title_style),
        Spacer(1, 12),
        Paragraph(f"Case: {case_data.get('case_number', 'Unknown')} - {case_data.get('case_title', '')}", body_style),
        Paragraph(f"Court: {case_data.get('court', 'Unknown')} | Judgment date: {case_data.get('judgment_date', 'Unknown')}", body_style),
        Paragraph(f"Parties: {case_data.get('parties', '')}", body_style),
        Spacer(1, 16),
        Paragraph("Action plan summary", section_style),
    ]

    items_rows = [["Title", "Priority", "Department", "Due Date", "Status"]]
    for item in action_items:
        items_rows.append(
            [
                item.get("title"),
                item.get("priority_badge"),
                item.get("department_name") or "Unassigned",
                str(item.get("due_date") or "TBD"),
                item.get("status_chip"),
            ]
        )
    items_table = Table(items_rows, hAlign="LEFT", colWidths=[180, 80, 100, 80, 80])
    items_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f0f0f0")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    elements.append(items_table)
    doc.build(elements, onFirstPage=_build_header_footer, onLaterPages=_build_header_footer)
    return buffer.getvalue()
