from __future__ import annotations

from enum import Enum


class UserRole(str, Enum):
	SUPERADMIN = "SUPERADMIN"
	ADMIN = "ADMIN"
	REVIEWER = "REVIEWER"
	OFFICER = "OFFICER"
	VIEWER = "VIEWER"


class ProcessingStatus(str, Enum):
	UPLOADED = "UPLOADED"
	CLASSIFYING = "CLASSIFYING"
	EXTRACTING = "EXTRACTING"
	EXTRACTION_COMPLETE = "EXTRACTION_COMPLETE"
	PENDING_REVIEW = "PENDING_REVIEW"
	UNDER_REVIEW = "UNDER_REVIEW"
	VERIFIED = "VERIFIED"
	REJECTED = "REJECTED"
	FAILED = "FAILED"


class FieldType(str, Enum):
	CASE_NUMBER = "CASE_NUMBER"
	CASE_TITLE = "CASE_TITLE"
	COURT_NAME = "COURT_NAME"
	JUDGMENT_DATE = "JUDGMENT_DATE"
	PARTIES = "PARTIES"
	PETITIONER = "PETITIONER"
	RESPONDENT = "RESPONDENT"
	BENCH_INFO = "BENCH_INFO"
	FACTS_SUMMARY = "FACTS_SUMMARY"
	OPERATIVE_DIRECTION = "OPERATIVE_DIRECTION"
	DEADLINE = "DEADLINE"
	APPEAL_CLUE = "APPEAL_CLUE"
	COMPLIANCE_OBLIGATION = "COMPLIANCE_OBLIGATION"
	RESPONSIBLE_DEPARTMENT = "RESPONSIBLE_DEPARTMENT"
	COST_ORDER = "COST_ORDER"
	PENALTY_RISK = "PENALTY_RISK"
	CONTEMPT_RISK = "CONTEMPT_RISK"
	FOLLOW_UP_REQUIRED = "FOLLOW_UP_REQUIRED"
	ACTION_ITEM = "ACTION_ITEM"


class ExtractionMethod(str, Enum):
	DIRECT_EXTRACT = "DIRECT_EXTRACT"
	OCR_PIPELINE = "OCR_PIPELINE"
	LLM_INFERRED = "LLM_INFERRED"
	HYBRID = "HYBRID"


class VerificationStatus(str, Enum):
	UNVERIFIED = "UNVERIFIED"
	APPROVED = "APPROVED"
	EDITED = "EDITED"
	REJECTED = "REJECTED"
	FLAGGED_FOR_REVIEW = "FLAGGED_FOR_REVIEW"
	PENDING = "PENDING"
	MODIFIED = "MODIFIED"


class ActionType(str, Enum):
	COMPLIANCE = "COMPLIANCE"
	APPEAL_CONSIDERATION = "APPEAL_CONSIDERATION"
	INTERNAL_REVIEW = "INTERNAL_REVIEW"
	ESCALATION = "ESCALATION"
	MONITORING = "MONITORING"


class Priority(str, Enum):
	CRITICAL = "CRITICAL"
	HIGH = "HIGH"
	MEDIUM = "MEDIUM"
	LOW = "LOW"


class DueDateSource(str, Enum):
	EXPLICIT_IN_JUDGMENT = "EXPLICIT_IN_JUDGMENT"
	INFERRED = "INFERRED"
	ESTIMATED = "ESTIMATED"


class CompletionStatus(str, Enum):
	NOT_STARTED = "NOT_STARTED"
	IN_PROGRESS = "IN_PROGRESS"
	COMPLETED = "COMPLETED"
	OVERDUE = "OVERDUE"
	CANCELLED = "CANCELLED"


class SessionStatus(str, Enum):
	IN_PROGRESS = "IN_PROGRESS"
	COMPLETED = "COMPLETED"
	ABANDONED = "ABANDONED"


class AuditEventType(str, Enum):
	DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
	FIELD_EXTRACTED = "FIELD_EXTRACTED"
	FIELD_VERIFIED = "FIELD_VERIFIED"
	FIELD_EDITED = "FIELD_EDITED"
	FIELD_REJECTED = "FIELD_REJECTED"
	ACTION_PLAN_GENERATED = "ACTION_PLAN_GENERATED"
	ACTION_PLAN_VERIFIED = "ACTION_PLAN_VERIFIED"
	USER_LOGIN = "USER_LOGIN"
	USER_ACTION = "USER_ACTION"
	SYSTEM_ERROR = "SYSTEM_ERROR"


class JobType(str, Enum):
	INGESTION = "INGESTION"
	CLASSIFICATION = "CLASSIFICATION"
	EXTRACTION = "EXTRACTION"
	ACTION_PLAN_GENERATION = "ACTION_PLAN_GENERATION"


class JobStatus(str, Enum):
	QUEUED = "QUEUED"
	IN_PROGRESS = "IN_PROGRESS"
	COMPLETED = "COMPLETED"
	FAILED = "FAILED"
	RETRYING = "RETRYING"


class AccessRequestStatus(str, Enum):
	PENDING = "PENDING"
	APPROVED = "APPROVED"
	REJECTED = "REJECTED"
	EXPIRED = "EXPIRED"
