#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p "$root_dir/backend/app/api/v1/endpoints"
mkdir -p "$root_dir/backend/app/api/v1/deps"
mkdir -p "$root_dir/backend/app/api/middleware"
mkdir -p "$root_dir/backend/app/core"
mkdir -p "$root_dir/backend/app/models/domain"
mkdir -p "$root_dir/backend/app/models/schemas"
mkdir -p "$root_dir/backend/app/services/ingestion"
mkdir -p "$root_dir/backend/app/services/extraction"
mkdir -p "$root_dir/backend/app/services/action_plan"
mkdir -p "$root_dir/backend/app/services/verification"
mkdir -p "$root_dir/backend/app/services/dashboard"
mkdir -p "$root_dir/backend/app/pipeline/stages"
mkdir -p "$root_dir/backend/app/db"
mkdir -p "$root_dir/backend/app/utils"
mkdir -p "$root_dir/backend/app/worker"
mkdir -p "$root_dir/backend/tests/unit"
mkdir -p "$root_dir/backend/tests/integration"
mkdir -p "$root_dir/backend/tests/fixtures"
mkdir -p "$root_dir/backend/alembic"
mkdir -p "$root_dir/backend/scripts"
mkdir -p "$root_dir/frontend/src/components"
mkdir -p "$root_dir/frontend/src/pages"
mkdir -p "$root_dir/frontend/src/hooks"
mkdir -p "$root_dir/frontend/src/services"
mkdir -p "$root_dir/frontend/src/stores"
mkdir -p "$root_dir/frontend/src/types"
mkdir -p "$root_dir/frontend/src/utils"
mkdir -p "$root_dir/frontend/src/styles"
mkdir -p "$root_dir/frontend/public"
mkdir -p "$root_dir/frontend/tests"
mkdir -p "$root_dir/shared/types"
mkdir -p "$root_dir/shared/constants"
mkdir -p "$root_dir/shared/schemas"
mkdir -p "$root_dir/worker"
mkdir -p "$root_dir/docker/postgres"
mkdir -p "$root_dir/docker/redis"
mkdir -p "$root_dir/docker/nginx"
mkdir -p "$root_dir/sample-data/judgments"
mkdir -p "$root_dir/sample-data/scanned"
mkdir -p "$root_dir/sample-data/expected-outputs"
mkdir -p "$root_dir/docs"
mkdir -p "$root_dir/scripts"

placeholder() {
  local file_path="$1"
  if [[ ! -f "$file_path" ]]; then
    printf '# Placeholder\n' > "$file_path"
  fi
}

placeholder "$root_dir/README.md"
placeholder "$root_dir/backend/README.md"
placeholder "$root_dir/backend/app/README.md"
placeholder "$root_dir/backend/app/api/README.md"
placeholder "$root_dir/backend/app/api/v1/README.md"
placeholder "$root_dir/backend/app/api/v1/endpoints/README.md"
placeholder "$root_dir/backend/app/api/v1/deps/README.md"
placeholder "$root_dir/backend/app/api/middleware/README.md"
placeholder "$root_dir/backend/app/core/README.md"
placeholder "$root_dir/backend/app/models/README.md"
placeholder "$root_dir/backend/app/models/domain/README.md"
placeholder "$root_dir/backend/app/models/schemas/README.md"
placeholder "$root_dir/backend/app/services/README.md"
placeholder "$root_dir/backend/app/services/ingestion/README.md"
placeholder "$root_dir/backend/app/services/extraction/README.md"
placeholder "$root_dir/backend/app/services/action_plan/README.md"
placeholder "$root_dir/backend/app/services/verification/README.md"
placeholder "$root_dir/backend/app/services/dashboard/README.md"
placeholder "$root_dir/backend/app/pipeline/README.md"
placeholder "$root_dir/backend/app/pipeline/stages/README.md"
placeholder "$root_dir/backend/app/db/README.md"
placeholder "$root_dir/backend/app/utils/README.md"
placeholder "$root_dir/backend/app/worker/README.md"
placeholder "$root_dir/backend/tests/README.md"
placeholder "$root_dir/backend/tests/unit/README.md"
placeholder "$root_dir/backend/tests/integration/README.md"
placeholder "$root_dir/backend/tests/fixtures/README.md"
placeholder "$root_dir/backend/alembic/README.md"
placeholder "$root_dir/backend/scripts/README.md"
placeholder "$root_dir/frontend/README.md"
placeholder "$root_dir/frontend/src/README.md"
placeholder "$root_dir/frontend/src/components/README.md"
placeholder "$root_dir/frontend/src/pages/README.md"
placeholder "$root_dir/frontend/src/hooks/README.md"
placeholder "$root_dir/frontend/src/services/README.md"
placeholder "$root_dir/frontend/src/stores/README.md"
placeholder "$root_dir/frontend/src/types/README.md"
placeholder "$root_dir/frontend/src/utils/README.md"
placeholder "$root_dir/frontend/src/styles/README.md"
placeholder "$root_dir/frontend/public/README.md"
placeholder "$root_dir/frontend/tests/README.md"
placeholder "$root_dir/shared/README.md"
placeholder "$root_dir/shared/types/README.md"
placeholder "$root_dir/shared/constants/README.md"
placeholder "$root_dir/shared/schemas/README.md"
placeholder "$root_dir/worker/README.md"
placeholder "$root_dir/docker/README.md"
placeholder "$root_dir/docker/postgres/README.md"
placeholder "$root_dir/docker/redis/README.md"
placeholder "$root_dir/docker/nginx/README.md"
placeholder "$root_dir/sample-data/README.md"
placeholder "$root_dir/sample-data/judgments/README.md"
placeholder "$root_dir/sample-data/scanned/README.md"
placeholder "$root_dir/sample-data/expected-outputs/README.md"
placeholder "$root_dir/docs/README.md"
placeholder "$root_dir/scripts/README.md"
